# Generated by Django 2.2.4 on 2020-04-29 09:46

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='contact_assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='contact_teams', to='teams.Teams'),
        ),
    ]
