# Generated by Django 2.2.4 on 2020-05-05 08:09

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200429_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_pic',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=contacts.models.img_url),
        ),
    ]
