# Generated by Django 2.2.4 on 2020-05-07 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('function_items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionitem',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='functionitem',
            name='type',
            field=models.CharField(choices=[('Frotn-end', 'Front-end'), ('Back-end', 'Back-end'), ('System', 'System'), ('Design', 'Design')], default='Front-end', max_length=20),
        ),
        migrations.CreateModel(
            name='VersionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
