# Generated by Django 2.2.4 on 2020-05-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_items', '0003_auto_20200507_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
