# Generated by Django 2.2.4 on 2020-05-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_items', '0005_auto_20200508_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Requested', 'Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Requested', max_length=20),
        ),
    ]
