# Generated by Django 2.2.4 on 2020-05-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_items', '0006_functionitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionitem',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Requested', max_length=20),
        ),
    ]
