# Generated by Django 2.2.4 on 2020-05-14 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('function_items', '0007_auto_20200514_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionitem',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_items_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
