# Generated by Django 2.2.4 on 2020-05-14 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('function_items', '0008_functionitem_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionitem',
            name='approved_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='functionitem',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_items_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='functionitem',
            name='last_updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
