# Generated by Django 2.2.4 on 2020-05-14 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('function_items', '0009_auto_20200514_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionitem',
            name='last_updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
