# Generated by Django 2.2.4 on 2020-06-22 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('function_items', '0012_functionitemhistory_changed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFunctionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Requested', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(null=True)),
                ('last_updated_on', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_function_items_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_function_items_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_function_items_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('related_function_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_function_items', to='function_items.FunctionItem')),
            ],
            options={
                'verbose_name': 'Sub Function Item',
                'verbose_name_plural': 'Sub Function Items',
                'ordering': ['created_on'],
            },
        ),
        migrations.AlterField(
            model_name='functionitemhistory',
            name='function_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_item_history', to='function_items.FunctionItem'),
        ),
        migrations.CreateModel(
            name='SubFunctionItemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Requested', max_length=20)),
                ('changed_data', models.TextField(blank=True, null=True, verbose_name='Changed Data')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sub_function_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_function_item_history', to='function_items.SubFunctionItem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_function_item_history_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
