# Generated by Django 2.2.4 on 2020-06-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='account_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='tags',
        ),
    ]
