# Generated by Django 2.2.4 on 2020-06-23 09:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200623_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
