# Generated by Django 2.2.4 on 2020-06-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0005_item_preset_unit_price'),
        ('rooms', '0005_roomitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitem',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='material_related_project_items', to='project_items.ItemTypeMaterial'),
            preserve_default=False,
        ),
    ]
