# Generated by Django 2.2.4 on 2020-06-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_roomitem_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitem',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
