# Generated by Django 2.2.4 on 2020-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_roomitem_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
