# Generated by Django 2.2.4 on 2020-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0005_item_preset_unit_price'),
        ('rooms', '0008_auto_20200626_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='related_items',
            field=models.ManyToManyField(blank=True, to='project_items.Item'),
        ),
    ]
