# Generated by Django 2.2.4 on 2020-06-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_roomtype_related_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitem',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_related_project_items', to='project_items.ItemTypeMaterial'),
        ),
    ]
