# Generated by Django 2.2.4 on 2020-07-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200629_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitem',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_project_items', to='rooms.Room'),
        ),
    ]
