# Generated by Django 2.2.4 on 2020-09-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20200703_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_related_project_items', to='project_items.ItemTypeMaterial'),
        ),
    ]
