# Generated by Django 2.2.4 on 2020-09-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20200902_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_properties',
            field=models.ManyToManyField(blank=True, to='rooms.RoomProperty'),
        ),
        migrations.DeleteModel(
            name='RoomTypeProperties',
        ),
    ]
