# Generated by Django 2.2.4 on 2020-09-03 16:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_auto_20200903_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomproperty',
            name='data_type',
            field=models.CharField(choices=[('Boolean', 'bool'), ('Number', 'num'), ('JSON', 'json')], default='num', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomproperty',
            name='sub_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
