# Generated by Django 2.2.4 on 2020-09-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_auto_20200904_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtypeformula',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_type_formulas', to='rooms.RoomType'),
        ),
    ]
