# Generated by Django 2.2.4 on 2020-09-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_auto_20200904_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomproperty',
            old_name='sub_properties',
            new_name='custom_properties',
        ),
        migrations.AlterField(
            model_name='roomproperty',
            name='data_type',
            field=models.CharField(choices=[('Boolean', 'bool'), ('Number', 'num'), ('Custom Property', 'custom property')], max_length=50),
        ),
    ]
