# Generated by Django 2.2.4 on 2020-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_auto_20200918_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomproperty',
            name='data_type',
            field=models.CharField(choices=[('bool', 'Boolean'), ('num', 'Number'), ('custom property', 'Custom Property')], max_length=50),
        ),
    ]
