# Generated by Django 2.2.4 on 2020-10-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0022_auto_20201029_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomitem',
            name='material_s',
        ),
    ]
