# Generated by Django 2.2.4 on 2020-11-03 08:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_remove_roomitem_material_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_type_formulas',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomtypeformula',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_type_formulas_s', to='rooms.RoomType'),
        ),
    ]
