# Generated by Django 2.2.4 on 2020-11-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0024_auto_20201103_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id']},
        ),
    ]
