# Generated by Django 2.2.4 on 2021-01-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0026_auto_20210107_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitem',
            name='item_quantifier',
            field=models.CharField(choices=[('單', '單'), ('個', '個')], default='單', max_length=20),
            preserve_default=False,
        ),
    ]
