# Generated by Django 2.2.4 on 2021-02-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0028_auto_20210108_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomproperty',
            options={'ordering': ['-index', '-id']},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='roomproperty',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='measure_quantifier',
            field=models.CharField(choices=[('mm', 'mm'), ('m', 'm'), ('ft', 'ft')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='measure_quantifier',
            field=models.CharField(choices=[('mm', 'mm'), ('m', 'm'), ('ft', 'ft')], max_length=20),
        ),
    ]
