# Generated by Django 2.2.4 on 2021-02-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0030_auto_20210201_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitem',
            name='value_based_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='item_quantifier',
            field=models.CharField(choices=[('單', '單'), ('個', '個'), ('直呎', '直呎'), ('平方呎', '平方呎'), ('項', '項')], max_length=20),
        ),
    ]
