# Generated by Django 2.2.4 on 2021-02-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0031_auto_20210202_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomproperty',
            options={'ordering': ['-index', 'id']},
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='item_quantifier',
            field=models.CharField(choices=[('單', '單'), ('個', '個'), ('直呎', '直呎'), ('平方呎', '平方呎'), ('平方米', '平方米'), ('項', '項')], max_length=20),
        ),
    ]
