# Generated by Django 2.2.4 on 2021-02-24 08:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0032_auto_20210224_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='related_items_sort',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_properties_sort',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
