# Generated by Django 2.2.4 on 2020-06-22 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0022_auto_20200622_1554'),
        ('teams', '0003_auto_20190909_1621'),
        ('companies', '0001_initial'),
        ('function_items', '0013_auto_20200622_1554'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50, verbose_name='Project Title')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Early Stage', '未開始'), ('In Progress', '進行中'), ('Finished', '已完成')], default='Early Stage', max_length=15)),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('district', models.CharField(choices=[('Central and Western', '中西區'), ('Wan Chai', '灣仔'), ('Eastern', '東區'), ('Southern', '南區'), ('Yau Tsim Mong', '油尖旺'), ('Sham Shui Po', '深水埗'), ('Kowloon City', '九龍城'), ('Wong Tai Sin', '黃大仙'), ('Kwun Tong', '觀塘'), ('Kwai Tsing', '葵青'), ('Tsuen Wan', '荃灣'), ('Tuen Mun', '屯門'), ('Yuen Long', '元朗'), ('North', '北區'), ('Tai Po', '大埔'), ('Sha Tin', '沙田'), ('Sai Kung', '西貢'), ('Islands', '離島')], max_length=50)),
                ('work_location', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Details Location')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_projects', to='companies.Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_created_by', to=settings.AUTH_USER_MODEL)),
                ('function_items', models.ManyToManyField(related_name='projects_function_items', to='function_items.FunctionItem')),
                ('sub_function_items', models.ManyToManyField(related_name='projects_sub_function_items', to='function_items.SubFunctionItem')),
                ('teams', models.ManyToManyField(related_name='projects_teams', to='teams.Teams')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50, verbose_name='Project Title')),
                ('project_number', models.CharField(max_length=50, verbose_name='Project Number')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Early Stage', '未開始'), ('In Progress', '進行中'), ('Finished', '已完成')], default='Draft', max_length=15)),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(related_name='project_history_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('from_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_history_from_address', to='common.Address')),
                ('function_items', models.ManyToManyField(related_name='projects_history_function_items', to='function_items.FunctionItemHistory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_history', to='projects.Project')),
                ('sub_function_items', models.ManyToManyField(related_name='projects_history_sub_function_items', to='function_items.SubFunctionItemHistory')),
                ('to_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_history_to_address', to='common.Address')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_history_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
