# Generated by Django 2.2.4 on 2020-07-06 09:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200706_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document_format',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
