# Generated by Django 2.2.4 on 2020-09-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200902_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_invoice_records', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectreceipt',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_receipt_records', to='projects.Project'),
        ),
    ]
