# Generated by Django 2.2.4 on 2020-10-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_documentformat_project_lower_format'),
        ('projects', '0008_projectcomparisons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_comparison', to='companies.Company')),
                ('projects', models.ManyToManyField(to='projects.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectComparisons',
        ),
    ]
