# Generated by Django 2.2.4 on 2021-01-12 11:11

import common.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_timetable', '0009_auto_20201120_0256'),
        ('projects', '0011_auto_20201013_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', common.fields.EncryptedImageField(height_field='img_height', upload_to=projects.models.project_img_url, width_field='img_width')),
                ('img_width', models.PositiveIntegerField(default=1)),
                ('img_height', models.PositiveIntegerField(default=1)),
                ('img_upload_date', models.DateField(default=datetime.date.today)),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ManyToManyField(to='projects.ProjectImage')),
                ('project_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_milestone_img_set', to='project_timetable.ProjectMilestone')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_img_set', to='projects.Project')),
            ],
        ),
    ]
