# Generated by Django 2.2.4 on 2021-01-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210113_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimageset',
            name='project_milestone',
        ),
    ]
