# Generated by Django 2.2.4 on 2021-01-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_timetable', '0009_auto_20201120_0256'),
        ('projects', '0038_auto_20210113_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimageset',
            name='project_milestone',
        ),
        migrations.AddField(
            model_name='projectimageset',
            name='related_milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_timetable.ProjectMilestone'),
        ),
    ]
