# Generated by Django 2.2.4 on 2021-01-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20210113_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimageset',
            name='related_milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_timetable.ProjectMilestone'),
        ),
    ]
