# Generated by Django 2.2.4 on 2020-06-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0002_auto_20200624_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('formula', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_items.Item')),
            ],
        ),
    ]
