# Generated by Django 2.2.4 on 2020-06-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0003_itemformula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemformula',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_formulas', to='project_items.Item'),
        ),
    ]
