# Generated by Django 2.2.4 on 2020-06-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0005_item_preset_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='preset_unit_price',
            new_name='value_based_price',
        ),
    ]
