# Generated by Django 2.2.4 on 2020-06-29 08:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0006_auto_20200629_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtypematerial',
            name='value_based_price',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
