# Generated by Django 2.2.4 on 2020-06-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0007_itemtypematerial_value_based_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='value_based_price'
        ),
        migrations.AddField(
            model_name='item',
            name='value_based_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='itemtypematerial',
            name='value_based_price'
        ),
        migrations.AddField(
            model_name='itemtypematerial',
            name='value_based_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
