# Generated by Django 2.2.4 on 2020-07-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectchargingstages'),
        ('project_items', '0008_auto_20200629_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('suggested_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Misc',
            },
        ),
        migrations.CreateModel(
            name='MiscType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.CreateModel(
            name='ProjectMisc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('misc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_project_misc', to='project_items.Misc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_misc', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Room Item',
                'verbose_name_plural': 'Room Items',
            },
        ),
        migrations.AddField(
            model_name='misc',
            name='misc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_related_misc', to='project_items.MiscType'),
        ),
    ]
