# Generated by Django 2.2.4 on 2020-07-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0009_auto_20200703_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='misc',
            options={'verbose_name': 'Misc', 'verbose_name_plural': 'Misc'},
        ),
        migrations.AlterModelOptions(
            name='projectmisc',
            options={'verbose_name': 'Project Misc', 'verbose_name_plural': 'Project Misc'},
        ),
        migrations.RemoveField(
            model_name='misc',
            name='misc_type',
        ),
        migrations.DeleteModel(
            name='MiscType',
        ),
    ]
