# Generated by Django 2.2.4 on 2020-07-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectchargingstages'),
        ('project_items', '0010_auto_20200703_1657'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmisc',
            unique_together={('misc', 'project')},
        ),
    ]
