# Generated by Django 2.2.4 on 2020-07-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectchargingstages'),
        ('project_items', '0011_auto_20200703_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpendType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='misc',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProjectExpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pic', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('pay_date', models.DateField()),
                ('expend_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_related_expend', to='project_items.ExpendType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_expend', to='projects.Project')),
            ],
        ),
    ]
