# Generated by Django 2.2.4 on 2020-07-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0012_auto_20200703_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectexpend',
            name='expend_type',
        ),
        migrations.RemoveField(
            model_name='projectexpend',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='projectmisc',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectmisc',
            name='misc',
        ),
        migrations.RemoveField(
            model_name='projectmisc',
            name='project',
        ),
        migrations.DeleteModel(
            name='ExpendType',
        ),
        migrations.DeleteModel(
            name='Misc',
        ),
        migrations.DeleteModel(
            name='ProjectExpend',
        ),
        migrations.DeleteModel(
            name='ProjectMisc',
        ),
    ]
