# Generated by Django 2.2.4 on 2020-09-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0013_auto_20200706_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemformula',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemtypematerial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_properties',
            field=models.ManyToManyField(blank=True, related_name='property_related_items', to='project_items.ItemProperty'),
        ),
    ]
