# Generated by Django 2.2.4 on 2020-10-27 13:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0014_auto_20200902_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='item_materials',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
