# Generated by Django 2.2.4 on 2020-10-27 13:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0015_itemtype_item_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='item_materials',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
