# Generated by Django 2.2.4 on 2020-10-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0016_auto_20201027_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='item_materials',
            new_name='item_type_materials',
        ),
        migrations.AlterField(
            model_name='itemtypematerial',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_type_materials_s', to='project_items.ItemType'),
        ),
    ]
