# Generated by Django 2.2.4 on 2020-11-05 07:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0018_auto_20201028_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_formulas',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemformula',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_formulas_s', to='project_items.Item'),
        ),
    ]
