# Generated by Django 2.2.4 on 2021-02-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0024_auto_20201211_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemproperty',
            options={'ordering': ['-index', '-id']},
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
