# Generated by Django 2.2.4 on 2021-02-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0025_auto_20210201_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemproperty',
            options={'ordering': ['-index', 'id']},
        ),
    ]
