# Generated by Django 2.2.4 on 2021-02-24 08:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0026_auto_20210224_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_properties_sort',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
