# Generated by Django 2.2.4 on 2021-02-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_items', '0027_item_item_properties_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-index', '-id'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='item',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
