# Generated by Django 2.2.4 on 2020-06-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('invoices', '0008_invoice_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='accounts',
        ),
        migrations.AddField(
            model_name='invoice',
            name='companies',
            field=models.ManyToManyField(related_name='companies_invoices', to='companies.Company'),
        ),
    ]
