# Generated by Django 2.2.4 on 2020-06-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='account',
        ),
    ]
