# Generated by Django 2.2.4 on 2020-06-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_case_account'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
