# Generated by Django 2.2.4 on 2020-09-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200902_2340'),
        ('project_timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_milestones', to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectwork',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_works', to='projects.Project'),
            preserve_default=False,
        ),
    ]
