# Generated by Django 2.2.4 on 2020-09-16 09:11

from django.db import migrations, models
import project_timetable.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_timetable', '0002_auto_20200902_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='img',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=project_timetable.models.milestone_img_url),
        ),
    ]
