# Generated by Django 2.2.4 on 2020-11-06 07:56

import common.fields
from django.db import migrations, models
import project_timetable.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_timetable', '0004_projectmilestone_img_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='img_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='img_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='img',
            field=common.fields.EncryptedImageField(blank=True, height_field='img_height', null=True, upload_to=project_timetable.models.milestone_img_url, width_field='img_width'),
        ),
    ]
