# Generated by Django 2.2.4 on 2020-11-16 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_timetable', '0006_auto_20201106_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='img_upload_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
