# Generated by Django 2.2.4 on 2020-05-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20200429_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='longitude',
            new_name='lng',
        ),
    ]
