# Generated by Django 2.2.4 on 2020-05-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
        ('common', '0020_auto_20200504_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='invoice',
        ),
        migrations.AddField(
            model_name='attachments',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_attachment', to='quotations.Quotation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_comments', to='quotations.Quotation'),
        ),
    ]
