# Generated by Django 2.2.4 on 2020-09-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20200622_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='br_approved',
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='login_token',
            field=models.CharField(default='aaaaaaaaaaaa', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='need_login_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], default='USER', max_length=50),
        ),
    ]
