# Generated by Django 2.2.4 on 2020-09-05 10:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20200905_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='new_phone_verify_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
