# Generated by Django 2.2.4 on 2020-06-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('opportunity', '0004_opportunity_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='account',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='companies.Tags'),
        ),
    ]
