# Generated by Django 2.2.4 on 2020-07-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectchargingstages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('suggested_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Misc',
                'verbose_name_plural': 'Misc',
            },
        ),
        migrations.CreateModel(
            name='ProjectMisc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('misc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_project_misc', to='project_misc.Misc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_misc', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Project Misc',
                'verbose_name_plural': 'Project Misc',
                'unique_together': {('misc', 'project')},
            },
        ),
    ]
