# Generated by Django 2.2.4 on 2020-11-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmisc',
            options={'ordering': ['id'], 'verbose_name': 'Project Misc', 'verbose_name_plural': 'Project Misc'},
        ),
    ]
