# Generated by Django 2.2.4 on 2020-11-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20201120_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='Pending', max_length=1024, null=True, verbose_name='Contact Address'),
        ),
    ]
