# Generated by Django 2.2.4 on 2020-06-24 09:01

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=99)),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=99)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_charging_stages', to='companies.Company')),
            ],
        ),
        migrations.DeleteModel(
            name='ChargingStage',
        ),
    ]
