# Generated by Django 2.2.4 on 2020-07-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200624_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='company',
            name='teams',
        ),
    ]
