# Generated by Django 2.2.4 on 2020-09-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200902_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentformat',
            name='project_upper_format',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='J', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentformat',
            name='invoice_lower_format',
            field=models.CharField(choices=[('Date', '日期(YYYYMMDD)'), ('Number', '4位數字(0000-9999)'), ('Alphabet', '英文字母(A-Z)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentformat',
            name='invoice_middle_format',
            field=models.CharField(choices=[('Date', '日期(YYYYMMDD)'), ('Number', '4位數字(0000-9999)'), ('Alphabet', '英文字母(A-Z)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentformat',
            name='quot_lower_format',
            field=models.CharField(choices=[('Date', '日期(YYYYMMDD)'), ('Number', '4位數字(0000-9999)'), ('Alphabet', '英文字母(A-Z)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentformat',
            name='quot_middle_format',
            field=models.CharField(choices=[('Date', '日期(YYYYMMDD)'), ('Number', '4位數字(0000-9999)'), ('Alphabet', '英文字母(A-Z)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentformat',
            name='receipt_lower_format',
            field=models.CharField(choices=[('Date', '日期(YYYYMMDD)'), ('Number', '4位數字(0000-9999)'), ('Alphabet', '英文字母(A-Z)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentformat',
            name='receipt_middle_format',
            field=models.CharField(choices=[('Date', '日期(YYYYMMDD)'), ('Number', '4位數字(0000-9999)'), ('Alphabet', '英文字母(A-Z)')], max_length=20),
        ),
    ]
