# Generated by Django 2.2.4 on 2020-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20200924_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentformat',
            name='project_lower_format',
            field=models.CharField(choices=[('Number', '4位數字(0000-9999)')], default='Number', max_length=20),
            preserve_default=False,
        ),
    ]
