# Generated by Django 2.2.4 on 2020-10-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20201027_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='br_pic_height',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='br_pic_width',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
