# Generated by Django 2.2.4 on 2020-10-27 06:40

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20201027_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='br_pic_height',
        ),
        migrations.RemoveField(
            model_name='company',
            name='br_pic_width',
        ),
        migrations.AlterField(
            model_name='company',
            name='br_pic',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=companies.models.br_url),
        ),
    ]
