# Generated by Django 2.2.4 on 2020-10-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20201027_1440'),
    ]

    operations = [
    ]
