# Generated by Django 2.2.4 on 2020-10-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20201027_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='br_pic_height',
        ),
        migrations.RemoveField(
            model_name='company',
            name='br_pic_width',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_pic_height',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_pic_width',
        ),
    ]
