# Generated by Django 2.2.4 on 2020-11-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20201106_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='br_pic_height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='br_pic_width',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_pic_height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_pic_width',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='sign_height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='sign_width',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
