# Generated by Django 2.2.4 on 2021-01-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20201106_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentformat',
            name='project_based_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentformat',
            name='project_upper_format',
            field=models.CharField(max_length=6),
        ),
    ]
