# Generated by Django 2.2.4 on 2020-07-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectchargingstages'),
        ('project_expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpendType',
            new_name='ExpenseType',
        ),
        migrations.RenameModel(
            old_name='ProjectExpend',
            new_name='ProjectExpense',
        ),
    ]
