# Generated by Django 2.2.4 on 2020-09-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_expenses', '0004_projectexpense_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpense',
            name='remark',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
