# Generated by Django 2.2.4 on 2020-11-05 10:58

import common.fields
from django.db import migrations, models
import project_expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_expenses', '0006_projectexpense_img_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='img_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='img_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='img',
            field=common.fields.EncryptedImageField(blank=True, height_field='img_height', null=True, upload_to=project_expenses.models.expense_img_url, width_field='img_width'),
        ),
    ]
