# Generated by Django 2.2.4 on 2020-11-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_expenses', '0007_auto_20201105_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpense',
            name='img_height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='img_width',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
