# Generated by Django 2.2.4 on 2020-11-19 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_expenses', '0009_auto_20201116_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpense',
            name='img_upload_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
