# Generated by Django 2.2.4 on 2020-12-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_expenses', '0011_auto_20201120_0256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetype',
            options={'ordering': ['-id']},
        ),
    ]
