# Generated by Django 2.2.4 on 2020-10-14 07:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscribedplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='function_permission',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
