# Generated by Django 2.2.4 on 2020-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0004_auto_20201014_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
