# Generated by Django 2.2.4 on 2020-10-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0005_auto_20201014_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='project_quota',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
