# Generated by Django 2.2.4 on 2020-10-14 09:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0007_subscriptionplan_bg_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='bg_color',
            new_name='bottom_bg_color',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='top_bg_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
