# Generated by Django 2.2.4 on 2020-10-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0011_auto_20201021_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='price',
            new_name='display_price',
        ),
    ]
