# Generated by Django 2.2.4 on 2020-05-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_items', '0004_functionitem_price'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='function_items',
            field=models.ManyToManyField(related_name='quotations_function_items', to='function_items.FunctionItem'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancel')], default='Draft', max_length=15),
        ),
    ]
