# Generated by Django 2.2.4 on 2020-05-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20200508_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_amount',
        ),
    ]
