# Generated by Django 2.2.4 on 2020-05-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_auto_20200513_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationhistory',
            name='currency',
        ),
    ]
