# Generated by Django 2.2.4 on 2020-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_items', '0007_auto_20200514_1544'),
        ('quotations', '0004_remove_quotationhistory_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationhistory',
            name='function_items',
            field=models.ManyToManyField(related_name='quotations_history_function_items', to='function_items.FunctionItem'),
        ),
        migrations.AlterField(
            model_name='quotationhistory',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancel')], default='Draft', max_length=15),
        ),
    ]
