# Generated by Django 2.2.4 on 2020-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_auto_20200514_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Requested to Approve', 'Requested to Approve'), ('Approved', 'Approved'), ('Requested to Approve Signed', 'Requested to Approve Signed'), ('Signed', 'Signed'), ('Requested to Approve Paid', 'Requested to Approve Paid'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancel')], default='Draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='quotationhistory',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Requested to Approve', 'Requested to Approve'), ('Approved', 'Approved'), ('Requested to Approve Signed', 'Requested to Approve Signed'), ('Signed', 'Signed'), ('Requested to Approve Paid', 'Requested to Approve Paid'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancel')], default='Draft', max_length=15),
        ),
    ]
