# Generated by Django 2.2.4 on 2020-05-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_auto_20200515_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationhistory',
            name='function_items',
            field=models.ManyToManyField(related_name='quotations_history_function_items', to='function_items.FunctionItem'),
        ),
    ]
