# Generated by Django 2.2.4 on 2020-05-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_auto_20200515_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationhistory',
            name='total_amount',
        ),
    ]
