from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.conf.urls import url
from django.urls import include, path
from common.views import handler404, handler500
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib import admin
from rest_framework_simplejwt.views import (
    TokenVerifyView,
    TokenRefreshView,
)

from api.views import (
	UserRegisterView,
	UserLoginView,
	UserPhoneVerifyView,
	SetCompanyView,
	GetCompanyView,
	GetDocumentFormatChoicesView,
	SetDocumentFormatView,
	GetDocumentFormatView,
	SetChargingStagesView,
	GetChargingStagesView,
	SetQuotationGeneralRemarksView,
	GetQuotationGeneralRemarksView,
	SetInvoiceGeneralRemarksView,
	GetInvoiceGeneralRemarksView,
	SetReceiptGeneralRemarksView,
	GetReceiptGeneralRemarksView,
	CreateProjectView,
	UpdateProjectView,
	GetProjectView,
	GetProjectListView,
	SetProjectCustomerView,
	CreateProjectRoomView,
	UpdateProjectRoomView,
	RemoveProjectRoomView,
	GetProjectAllItemView,
	GetProjectAllRoomItemView,
	SetProjectRoomItemView,
	PreCalProjectRoomItemFormulaView,
	GetProjectRoomListView,
	SetProjectMiscView,
	GetAllProjectMiscView,
	GetDistrictListView,
	GetRoomTypeListView,
	GetRoomRelatedItemListView,
	GetItemMaterials,
	GetProjectRoomDetailsView,
	PreviewProjectQuotation,
	GenerateProjectQuotation,
	PreviewProjectInvoice,
	GenerateProjectInvoice,
	PreviewProjectReceipt,
	GenerateProjectReceipt,
	CreateProjectWorkView,
	UpdateProjectWorkView,
	CreateProjectMilestoneView,
	UpdateProjectMilestoneView,
	UpdateProjectQuotationRemarks,
	UpdateProjectInvoiceRemarks,
	UpdateProjectReceiptRemarks,
	GetExpenseTypeListView,
	CreateProjectExpenseView,
	UpdateProjectExpenseView,
	GetProjectProfitAnalysisView
)


app_name = 'api'

urlpatterns = [
	path('register/',UserRegisterView.as_view(),name='user_register'),
	path('login/',UserLoginView.as_view(),name='user_login'),
	path('check/', TokenVerifyView.as_view(), name='token_check'),
	path('refresh/',TokenRefreshView.as_view(),name='token_refresh'),
	path('verify/phone/',UserPhoneVerifyView.as_view(),name='phone_verify'),
	path('company/set/',SetCompanyView.as_view(),name="set_company"),
	path('company/get/',GetCompanyView.as_view(),name="get_company"),
	path('doc_format/get/choices/',GetDocumentFormatChoicesView.as_view(),name="get_doc_format_choices"),
	path('doc_format/set/',SetDocumentFormatView.as_view(),name="set_doc_format"),
	path('doc_format/get/',GetDocumentFormatView.as_view(),name="get_doc_format"),
	path('charging_stages/set/',SetChargingStagesView.as_view(),name="set_charging_stages"),
	path('charging_stages/get/',GetChargingStagesView.as_view(),name="get_charging_stages"),
	path('quotation_general_remarks/set/',SetQuotationGeneralRemarksView.as_view(),name="set_quotation_general_remarks"),
	path('quotation_general_remarks/get/',GetQuotationGeneralRemarksView.as_view(),name="get_quotation_general_remarks"),
	path('invoice_general_remarks/set/',SetInvoiceGeneralRemarksView.as_view(),name="set_invoice_general_remarks"),
	path('invoice_general_remarks/get/',GetInvoiceGeneralRemarksView.as_view(),name="get_invoice_general_remarks"),
	path('receipt_general_remarks/set/',SetReceiptGeneralRemarksView.as_view(),name="set_receipt_general_remarks"),
	path('receipt_general_remarks/get/',GetReceiptGeneralRemarksView.as_view(),name="get_receipt_general_remarks"),
	path('project/create/',CreateProjectView.as_view(),name="create_project"),
	path('project/update/',UpdateProjectView.as_view(),name="update_project"),
	path('project/get/',GetProjectView.as_view(),name="get_project"),
	path('project/list/',GetProjectListView.as_view(),name="list_project"),
	path('project/customer/set/',SetProjectCustomerView.as_view(),name="set_project_customer"),
	path('project/room/create/',CreateProjectRoomView.as_view(),name="create_project_room"),
	path('project/room/update/',UpdateProjectRoomView.as_view(),name="update_project_room"),
	path('project/room/remove/',RemoveProjectRoomView.as_view(),name="remove_project_room"),
	path('project/room/list/',GetProjectRoomListView.as_view(),name="list_project_rooms"),
	path('project/room/get/',GetProjectRoomDetailsView.as_view(),name="get_project_room_details"),
	path('project/room/item/set/',SetProjectRoomItemView.as_view(),name="set_project_room_item"),
	path('project/room/item/precal/',PreCalProjectRoomItemFormulaView.as_view(),name="pre_cal_project_room_item_forumla"),
	path('project/item/get/all/byroom/',GetProjectAllRoomItemView.as_view(),name="get_project_all_room_items"),
	path('project/item/get/all/',GetProjectAllItemView.as_view(),name="get_project_all_items"),
	path('project/misc/set/',SetProjectMiscView.as_view(),name="set_project_misc"),
	path('project/misc/get/all/',GetAllProjectMiscView.as_view(),name="get_all_project_misc"),
	path('project/quot/preview/',PreviewProjectQuotation.as_view(),name="preview_project_quotation"),
	path('project/quot/remarks/update/',UpdateProjectQuotationRemarks.as_view(),name="update_project_quotation_remarks"),
	path('project/quot/generate/',GenerateProjectQuotation.as_view(),name="generate_project_quotation"),
	path('project/invoice/preview/',PreviewProjectInvoice.as_view(),name="preivew_project_invoice"),
	path('project/invoice/remarks/update/',UpdateProjectInvoiceRemarks.as_view(),name="update_project_invoice_remarks"),
	path('project/invoice/generate/',GenerateProjectInvoice.as_view(),name="generate_project_invoice"),
	path('project/receipt/preview/',PreviewProjectReceipt.as_view(),name="preview_project_receipt"),
	path('project/receipt/remarks/update/',UpdateProjectReceiptRemarks.as_view(),name="update_project_receipt_remarks"),
	path('project/receipt/generate/',GenerateProjectReceipt.as_view(),name="generate_project_receipt"),
	path('project/work/create/',CreateProjectWorkView.as_view(),name="create_project_work"),
	path('project/work/update/',UpdateProjectWorkView.as_view(),name="update_project_work"),
	path('project/milestone/create/',CreateProjectMilestoneView.as_view(),name="create_project_milestone"),
	path('project/milestone/update/',UpdateProjectMilestoneView.as_view(),name="update_project_milestone"),
	path('project/expense/create/',CreateProjectExpenseView.as_view(),name="create_project_expense"),
	path('project/expense/update/',UpdateProjectExpenseView.as_view(),name="update_project_expense"),
	path('project/profit/analysis/get/',GetProjectProfitAnalysisView.as_view(),name="get_project_profit_analysis"),
	path('districts/get/',GetDistrictListView.as_view(),name="get_districts"),
	path('room_types/get/',GetRoomTypeListView.as_view(),name="get_room_types"),
	path('room_type/related_items/get/',GetRoomRelatedItemListView.as_view(),name="get_room_type_related_items"),
	path('item/materials/get/',GetItemMaterials.as_view(),name="get_item_materials"),
	path('expense_types/get/',GetExpenseTypeListView.as_view(),name="get_expense_types")
]
